from data_structure_and_algorithms.sllist.sllist import SingleLinkedList
from data_structure_and_algorithms.dllist.dllist  import DoubleLinkedList
from data_structure_and_algorithms.stacks_queues.stack import Stack
